version: "3"

services:
    web:
        container_name: webapp
        restart: always
        build: .
        ports: 
            - 5000:3000
        links: 
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mydb
        image: mongo
        ports:
            - 27017:27017
        logging:
            driver: none
        
